# concurrency就是控制并发的，流水线运行后会自动加锁
# 在一个组的流水线任务只能有一个在运行，其他流水线任务会被pedding
# 文档：https://docs.github.com/zh/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs
# concurrency:
#   group: archiving-group

name: Auto issues archiving

on:
  issues:
    types: [closed]

jobs:
  get_issue_details:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
  
      - name: Cache pip dependencies
        id: cache-pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./issue_processor/requirements.txt
  
      - name: Run Python script
        env:
          TOKEN: ${{ secrets.ISSUESS_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_STATE: ${{ github.event.issue.state }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_URL: "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}"
          COMMENTS_URL: "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments"
          DISPATCH_URL: ${{ vars.DISPATCH_URL }}
          DISPATCH_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
          DISPATCH_NAME: ${{ vars.DISPATCH_NAME }}
        run: |
          cd ./
          python ./issue_processor/main.py -c "./.github/configs/issue_processor.json"


