# concurrency就是控制并发的，流水线运行后会自动加锁
# 在一个组的流水线任务只能有一个在运行，其他流水线任务会被pedding
# 文档：https://docs.github.com/zh/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs
concurrency:
  group: archiving-group

run-name: "Manual closed 外部Issue#${{ github.event.inputs.issue_number }}"
name: Manual Archiving Closed issues

# permissions是关于GITHUB_TOKEN权限的，内容详见：
# https://docs.github.com/zh/actions/writing-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  issues: write
  contents: write

# on.workflow_dispatch.inputs 文档：
# https://docs.github.com/zh/actions/writing-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs
on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: "需要关闭的issue的单号（仅数字），只允许输入一个单号,"
        required: true
      issue_title:
        description: "此值将影响对应单号的issue在归档文件中的描述，为空则自动获取issue标题"
        required: false
        default: ""
      introduced_version:
        description: "引入版本号，为空则自动从对应的issue描述中获取引入版本号"
        required: false
        default: ""
      archive_version:
        description: "归档版本号，为空则自动从对应的issue评论中获取归档版本号"
        required: false
        default: ""

env:
  ISSUE_OUTPUT_PATH: "./output.json"
  ISSUE_REPOSITORY: "外部Issue"
  COMMIT_TITLE: "Closed 外部Issue#${{ github.event.inputs.issue_number }}"
  MANUAL_ARCHIVING: "true"

jobs:
  archiving_issue_manually:
    name: "Manual closed 外部Issue#${{ github.event.inputs.issue_number }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./src/issue_processor/requirements.txt
          pip install -r ./src/auto_archiving/requirements.txt
  
      - name: Processing issue content
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.inputs.issue_number }}
          ISSUE_TITLE: ${{ github.event.inputs.issue_title }}
          ISSUE_STATE: "closed"  # 未实现reopen issue并删除归档条目的功能
          ARCHIVE_VERSION: ${{ github.event.inputs.archive_version }}
          INTRODUCED_VERSION: ${{ github.event.inputs.introduced_version }}
          ISSUE_URL: "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.inputs.issue_number }}"
          COMMENTS_URL: "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.inputs.issue_number }}/comments"
        run: |
          python ./src/issue_processor_main.py -c "./config/issue_processor.json"

      - name: Archiving closed issues
        run: |
          python ./src/auto_archiving_main.py -c "./config/auto_archiving.json" -fr "./归档失败记录.json"
          
      - name: Add and commit changes
        run: |
          bash ./src/push_document.sh
          



        
