name: "Unit test"
run-name: "Unit test"

on:
  push:
    paths: 
    - 'rn_issues_auto_archiving/**/*.py'

jobs:
  auto_archiving:
    name: "Run unit test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python and install dependencies
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip' # caching pip dependencies
      - run: |
          pip install -r ./rn_issues_auto_archiving/issue_processor/requirements.txt
          pip install pytest
        
      - name: Run unit test
        run: |
          pytest
